# Generated by Django 5.2.6 on 2026-01-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_photo_image_alter_photo_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['created_at']},
        ),
    ]
