# Generated by Django 5.2.6 on 2026-01-22 19:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_photo_options"),  # keep this pointing to your latest catalog migration
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]