# Generated by Django 5.2.6 on 2026-01-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_collection_description'),
        ('catalog', '0005_add_description_fields'),
    ]

    operations = [
    ]
