# Generated by Django 5.2.6 on 2026-01-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_merge_20260122_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at']},
        ),
    ]
