# Generated by Django 5.2.6 on 2026-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_photo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
