# Generated by Django 5.2.6 on 2026-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_productvariant_sku'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='variant_price_nonnegative',
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('photo', 'size', 'finish', 'kind'), name='unique_variant_per_photo_size_finish_kind'),
        ),
    ]
